# Logo
logo: '' # Empty this to unset logo

# Header
menu:
  My work: my-work
  Tags: tags

# Content
excerpt_link: Read More
fancybox: true

# Profile
profile: true # whether to show profile bar
gravatar: false # whether to use gravatar with the email
showlogo: false # whether to show the logo in the header

# Sidebar
sidebar: right # set to false if you don't want a sidebar
widgets:
- recent_posts
- tag

# Contacts
contacts:
  twitter: http://twitter.com/_stipegrbic_
  linkedin: https://hr.linkedin.com/pub/stipe-grbić/83/45a/450

# Links
links:
  Hexo: http://hexo.io

# CDN
cdn: google #If your site loads slowly change it to "google" , because "useso" is slow out of China

# Miscellaneous
google_site_verification:
google_analytics:
favicon: favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
